In [5]:
import numpy as np
import cv2 as cv
import glob

# termination criteria
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((6*7,3), np.float32)
objp[:,:2] = np.mgrid[0:7,0:6].T.reshape(-1,2)

# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.

images = glob.glob('source/*.JPG')

print(images)

for fname in images:
    img = cv.imread(fname)
    gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
    
    # Find the chess board corners
    ret, corners = cv.findChessboardCorners(gray, (7,6), None)
    
    # If found, add object points, image points (after refining them)
    if ret == True:
        objpoints.append(objp)
        
        corners2 = cv.cornerSubPix(gray,corners, (11,11), (-1,-1), criteria)
        imgpoints.append(corners)
        
        # Draw and display the corners
        cv.drawChessboardCorners(img, (7,6), corners2, ret)
        cv.imshow('img', img)
        cv.waitKey(500)

cv.destroyAllWindows()
print("FINISH")

['source/test002.JPG', 'source/test007.JPG', 'source/test004.JPG', 'source/test001.JPG', 'source/test003.JPG', 'source/test005.JPG', 'source/test006.JPG', 'source/test008.JPG']


FINISH


In [6]:
#Extract information about your camera (iPhone SE)
ret, mtx, dist, rvecs, tvecs = cv.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

In [8]:
#Camera matrix iPhone SE
print(mtx)

[[3.23139183e+03 0.00000000e+00 2.08190313e+03]
 [0.00000000e+00 3.23807365e+03 1.61471489e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]


In [17]:
f_x = mtx[0][0]
f_y = mtx[1][1]
c_x = mtx[0][2]
c_y = mtx[1][2]

focal_length = 4.15

In [21]:
m = ((f_x+f_y)/2) / focal_length
print(m)

779.4536717073466


In [19]:
# The size of image inside of sensor
object_image_sensormm = 2717/m
print(object_image_sensormm)

3.580676405208003


In [20]:
#Distance (mm) = real_object_size (mm) * focal_distance (mm) / object_size_image_sensor (mm)
distance_mm = 242 * F / object_image_sensormm
print(distance_mm/10)

28.047773279352224
