In [2]:
import numpy as np
import cv2 as cv
import glob

# termination criteria
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((6*7,3), np.float32)
objp[:,:2] = np.mgrid[0:7,0:6].T.reshape(-1,2)

# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.

images = glob.glob('*.JPG')

print(images)

for fname in images:
    img = cv.imread(fname)
    
    cv.imshow('sd', img)
    
    gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
    
    # Find the chess board corners
    ret, corners = cv.findChessboardCorners(gray, (7,6), None)
    
    # If found, add object points, image points (after refining them)
    if ret == True:
        objpoints.append(objp)
        
        corners2 = cv.cornerSubPix(gray,corners, (11,11), (-1,-1), criteria)
        imgpoints.append(corners)
        
        # Draw and display the corners
        cv.drawChessboardCorners(img, (7,6), corners2, ret)
        cv.imshow('img', img)
        cv.waitKey(500)

cv.destroyAllWindows()

['IMG_2459.JPG', 'IMG_2460.JPG', 'IMG_2464.JPG', 'IMG_2461.JPG', 'IMG_2458.JPG', 'IMG_2463.JPG', 'IMG_2462.JPG', 'IMG_2457.JPG']


In [4]:
#Extract information about your camera
ret, mtx, dist, rvecs, tvecs = cv.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

In [ ]:
#Camera matrix
print(mtx)

[[3.15254239e+03 0.00000000e+00 2.10182581e+03]
 [0.00000000e+00 3.14696041e+03 1.58744406e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]


In [16]:
f_x = 3152
f_y = 3146
c_x = 2101
c_y = 1587

F = 4.15

In [17]:
m = 3149 / F
print(m)

758.7951807228915


In [18]:
# The size of image inside of sensor
object_image_sensormm = 2717/m
print(object_image_sensormm)

3.580676405208003


In [1]:
#Distance (mm) = real_object_size (mm) * focal_distance (mm) / object_size_image_sensor (mm)
distance_mm = 242 * F / object_image_sensormm
print(distance_mm/10)

NameError: name 'F' is not defined